name: CI
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v1
      - name: install dependencies
        run: sudo apt-get -y install g++-12 build-essential cmake ninja-build libgtest-dev
      - name: add build folder
        run: mkdir -p build
      - name: build
        working-directory: ./build
        run: cmake -Wno-dev -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_BUILD_TYPE=Release -DSTONKS_ENABLE_TESTS=ON -DSTONKS_ENABLE_BENCHMARKS=ON -DSTONKS_RUN_ON_CI=ON -G "Ninja" -S .. -B . && cmake --build . -j4
      - name: tests
        working-directory: ./build/tests
        run: ctest
      - name: benchmarks
        working-directory: ./build/benchmarks
        run: ./benchmark_tests